export { default as U2Breadcrumb } from './u2-breadcrumb'
export { default as U2Content } from './u2-content'
export { default as U2Footer } from './u2-footer'
export { default as U2Header } from './u2-header'
export { default as U2Menu } from './u2-menu'
export { default as U2Silder } from './u2-silder'
